# Generated by Django 3.0.8 on 2020-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='filename',
            field=models.FileField(upload_to='notes/pdf'),
        ),
    ]
