# Generated by Django 3.0.8 on 2020-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200805_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='filename',
            field=models.FileField(upload_to='notes/pdf/'),
        ),
    ]
